### ISSUE TITLE
Impostor

### ISSUE THREAD

**Issue by Epic-Dasher** [TheAlienDrew/Tampermonkey-Scripts#1]
Hello! I talked to you last year and Im wondering if you have been online, I have seen lots of fakers! 
![image](https://user-images.githubusercontent.com/67171685/98184694-18998300-1f5f-11eb-935c-2dc3812805a6.png)   
Their id: 39b3c5fd003a96c0a8deb5e3

**Comment by TheAlienDrew** [comment]
No I haven't been on the site in a long time. I've been busy with college
and work
