### ISSUE TITLE
Tampermonkey Script Fails to load sometimes (Tampermonkey bug)

### ISSUE THREAD

**Issue by anderlli0053** [TheAlienDrew/Tampermonkey-Scripts#7]
It installs and reinstalls smoothly, but it does not show the custom button for enabling the bot (midi player) feature..

**missing button:**
![btn](https://user-images.githubusercontent.com/22171451/177045202-45107322-de11-4465-90ca-686ee5f5d395.JPG)

**Comment by TheAlienDrew** [comment]
This is not a glitch with the bot, this is an issue with Tampermonkey. You need to reinstall the Tampermonkey extension, and then it'll start working again. This is not an issue that I have any control over, so don't ask me to fix it.

**Comment by anderlli0053** [comment]
> This is not a glitch with the bot, this is an issue with Tampermonkey. You need to reinstall the Tampermonkey extension, and then it'll start working again. This is not an issue that I have any control over, so don't ask me to fix it.

Sorry, i did not knew that this was the problem with Tampermonkey... I reinstalled it and it solved the issue, thank you again
