### ISSUE TITLE
Twitter - Auto Device Theme stopped working

### ISSUE THREAD

**Issue by SebastianRasch** [TheAlienDrew/Tampermonkey-Scripts#8]
Twitter has a new popup menu for settings when clicking on "More" and the script can't handle it. It actually freezes parts of the page when the system and Twitter are not on the same setting (for example system is dark but Twitter still bright).

Love your script, please update for the new menu! 🤗

**Comment by TheAlienDrew** [comment]
Should be fixed now, try updating.
